namespace SupportAgent.Core.Models;

/// <summary>
/// Structured suggested reply generated by the copilot for human review.
/// </summary>
public class CopilotDraftReply
{
    /// <summary>Suggested email or reply subject line.</summary>
    public string Subject { get; set; } = string.Empty;

    /// <summary>Suggested reply body text.</summary>
    public string Body { get; set; } = string.Empty;

    /// <summary>Recommended tone such as professional.</summary>
    public string Tone { get; set; } = "professional";

    /// <summary>Model confidence from 0.0 to 1.0.</summary>
    public double Confidence { get; set; }
}
