namespace SupportAgent.Core.Enums;

/// <summary>
/// Identifies who sent a message in an AI conversation.
/// </summary>
public enum AIMessageRole
{
    /// <summary>System instructions that define assistant behavior.</summary>
    System,

    /// <summary>A message from the end user.</summary>
    User,

    /// <summary>A message generated by the assistant, optionally with tool calls.</summary>
    Assistant,

    /// <summary>Output returned from a tool execution.</summary>
    Tool
}
